### ISSUE TITLE
MPA 395 - Title not showing correctly

### ISSUE THREAD

**Issue by thburns** [csumb/csumb-gatsby#198] opened 2019-05-07 16:15 UTC
I just noticed that MPA 395 - our special topics course in the fall semester lost its specific name and description in the website update. It definitely needs it back as its impossible for students to know what the course is without it. From Lanier Sammons

**Comment by kevee** [comment] 2019-05-07 16:59
Dupe of #199

**Closed by kevee** 2019-05-07 16:59 UTC
Labels: High priority
